### ISSUE TITLE
Adding gr to homebrew

### ISSUE THREAD

**Issue by brodock** [SciRuby/rubyplot#39]
I've added a GR formula to homebrew (`libgr`): https://github.com/Homebrew/homebrew-core/pull/37046 it's waiting for review. Hope this helps you with the `rubyplot` work :)

**Comment by v0dro** [comment]
Thank you for adding. However this issue does not belong here so I will be closing it.
Please send a PR with GR installation instructions to rubyplot once your homebrew PR is merged.
